const SUBMIT_DETAILS = 'SUBMIT_DETAILS';
const ON_CHANGE = 'ON_CHANGE';
const AUTH_USER ='AUTH_USER';
const LOGIN_DEMO = 'LOGIN_DEMO'
const RESET_LOGINS = 'RESET_LOGINS'

export {SUBMIT_DETAILS, ON_CHANGE, AUTH_USER, LOGIN_DEMO, RESET_LOGINS}