const ON_CHANGE = 'ON_CHANGE';
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGIN';
const REQUEST_USER_INFO = "REQUEST_USER_INFO";
const RECEIVE_USER_INFO = "RECEIVE_USER_INFO"; 

export { ON_CHANGE, LOGIN, LOGOUT, REQUEST_USER_INFO, RECEIVE_USER_INFO }