const ON_CHANGE = "ON_CHANGE";
const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const REQUEST_USER_INFO = "REQUEST_USER_INFO";
const RECEIVE_USER_INFO = "RECEIVE_USER_INFO";
const REQUEST_USER_LINKS = "REQUEST_USER_LINKS";
const RECEIVE_USER_LINKS = "RECEIVE_USER_LINKS";
const UPDATE_COPY = "UPDATE_COPY";
const DEFAULT = "DEFAULT";
const AUTO_LOGIN = "AUTO_LOGIN";
const FAILED_AUTO_LOGIN = "FAILED_AUTO_LOGIN";
const REQUEST_UPDATE = "UPDADE_REQUEST";
const RECIEVE_UPDATE = "RECIEVE_UPDATE";
const RESET_ALERT = "RESET_ALERT";
const SET_ALERT = 'SET_ALERT';

export {
  DEFAULT,
  UPDATE_COPY,
  ON_CHANGE,
  LOGIN,
  LOGOUT,
  REQUEST_USER_INFO,
  RECEIVE_USER_INFO,
  REQUEST_USER_LINKS,
  RECEIVE_USER_LINKS,
  AUTO_LOGIN,
  FAILED_AUTO_LOGIN,
  REQUEST_UPDATE,
  RECIEVE_UPDATE,
  RESET_ALERT,
  SET_ALERT
};
