const ON_CHANGE = 'ON_CHANGE';
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const REQUEST_USER_INFO = "REQUEST_USER_INFO";
const RECEIVE_USER_INFO = "RECEIVE_USER_INFO";
const REQUEST_USER_LINKS = "REQUEST_USER_LINKS";
const RECEIVE_USER_LINKS = "RECEIVE_USER_LINKS";
const UPDATE_COPY = "UPDATE_COPY";
const DEFAULT = "DEFAULT"; 
const AUTO_LOGIN = "AUTO_LOGIN";
const FAILED_AUTO_LOGIN = "FAILED_AUTO_LOGIN";

export { DEFAULT, UPDATE_COPY, ON_CHANGE, LOGIN, LOGOUT, REQUEST_USER_INFO, RECEIVE_USER_INFO, REQUEST_USER_LINKS, RECEIVE_USER_LINKS, AUTO_LOGIN, FAILED_AUTO_LOGIN}