const SUBMIT_URL = "SUBMIT_URL";
const RECEIVE_SHORT = "RECEIVE_SHORT";
const POST_CUSTOM = "POST_CUSTOM";
const RECEIVE_CUSTOM ="RECEIVE_CUSTOM";

export { SUBMIT_URL, RECEIVE_SHORT, POST_CUSTOM, RECEIVE_CUSTOM };
